//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchImageProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchImageProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutBtn_ToolTip {
            get {
                return ResourceManager.GetString("AboutBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Folder....
        /// </summary>
        public static string AddFolderBtn_ToolTip {
            get {
                return ResourceManager.GetString("AddFolderBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        public static string AlignBottomCenterTooltip {
            get {
                return ResourceManager.GetString("AlignBottomCenterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        public static string AlignBottomLeftTooltip {
            get {
                return ResourceManager.GetString("AlignBottomLeftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        public static string AlignBottomRightTooltip {
            get {
                return ResourceManager.GetString("AlignBottomRightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Center.
        /// </summary>
        public static string AlignMiddleCenterTooltip {
            get {
                return ResourceManager.GetString("AlignMiddleCenterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Left.
        /// </summary>
        public static string AlignMiddleLeftTooltip {
            get {
                return ResourceManager.GetString("AlignMiddleLeftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Right.
        /// </summary>
        public static string AlignMiddleRightTooltip {
            get {
                return ResourceManager.GetString("AlignMiddleRightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        public static string AlignTopCenterTooltip {
            get {
                return ResourceManager.GetString("AlignTopCenterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        public static string AlignTopLeftTooltip {
            get {
                return ResourceManager.GetString("AlignTopLeftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        public static string AlignTopRightTooltip {
            get {
                return ResourceManager.GetString("AlignTopRightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap (*.bmp).
        /// </summary>
        public static string BmpOutput {
            get {
                return ResourceManager.GetString("BmpOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Selected Items.
        /// </summary>
        public static string CheckAllBtn_ToolTip {
            get {
                return ResourceManager.GetString("CheckAllBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Enabled State of Selected Items.
        /// </summary>
        public static string CheckInvBtn_ToolTip {
            get {
                return ResourceManager.GetString("CheckInvBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Adjustments.
        /// </summary>
        public static string ColChck_ToolTip {
            get {
                return ResourceManager.GetString("ColChck_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string ColorBrightnessHeader {
            get {
                return ResourceManager.GetString("ColorBrightnessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string ColorContrastHeader {
            get {
                return ResourceManager.GetString("ColorContrastHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        public static string ColorGammaHeader {
            get {
                return ResourceManager.GetString("ColorGammaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Greyscale.
        /// </summary>
        public static string ColorGreyscaleOption {
            get {
                return ResourceManager.GetString("ColorGreyscaleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments.
        /// </summary>
        public static string ColorOptionLabel_Text {
            get {
                return ResourceManager.GetString("ColorOptionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string ColorSaturationHeader {
            get {
                return ResourceManager.GetString("ColorSaturationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Saturation.
        /// </summary>
        public static string ColorSaturationOption {
            get {
                return ResourceManager.GetString("ColorSaturationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Sepia.
        /// </summary>
        public static string ColorSepiaOption {
            get {
                return ResourceManager.GetString("ColorSepiaOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Settings.
        /// </summary>
        public static string ColorSettings_Title {
            get {
                return ResourceManager.GetString("ColorSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  completed of .
        /// </summary>
        public static string CompleteOfLabel {
            get {
                return ResourceManager.GetString("CompleteOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop alignment:.
        /// </summary>
        public static string CropAlignHeader {
            get {
                return ResourceManager.GetString("CropAlignHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Cropping.
        /// </summary>
        public static string CropChck_ToolTip {
            get {
                return ResourceManager.GetString("CropChck_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string CropOptionLabel_Text {
            get {
                return ResourceManager.GetString("CropOptionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string CropOpts_HeightUpDwn_Text {
            get {
                return ResourceManager.GetString("CropOpts_HeightUpDwn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string CropOpts_WidthUpDwn_Text {
            get {
                return ResourceManager.GetString("CropOpts_WidthUpDwn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop down to:.
        /// </summary>
        public static string CropOptsLabel_Text {
            get {
                return ResourceManager.GetString("CropOptsLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Settings.
        /// </summary>
        public static string CropSettings_Title {
            get {
                return ResourceManager.GetString("CropSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Output Format.
        /// </summary>
        public static string DefaultOutput {
            get {
                return ResourceManager.GetString("DefaultOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Settings.
        /// </summary>
        public static string DefaultSettingsLabel_Content {
            get {
                return ResourceManager.GetString("DefaultSettingsLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string DeselectBtn_ToolTip {
            get {
                return ResourceManager.GetString("DeselectBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FilesLabel_Text {
            get {
                return ResourceManager.GetString("FilesLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500%.
        /// </summary>
        public static string FiveHundredPercentLabel {
            get {
                return ResourceManager.GetString("FiveHundredPercentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Folder.
        /// </summary>
        public static string FolderMenu_RemoveMenuItem_Header {
            get {
                return ResourceManager.GetString("FolderMenu_RemoveMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        public static string FolderMenu_RenameMenuItem_Header {
            get {
                return ResourceManager.GetString("FolderMenu_RenameMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FoldersLabel_Text {
            get {
                return ResourceManager.GetString("FoldersLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually GC all Generations.
        /// </summary>
        public static string GcBtn_ToolTip {
            get {
                return ResourceManager.GetString("GcBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Interchange Format (*.gif).
        /// </summary>
        public static string GifOutput {
            get {
                return ResourceManager.GetString("GifOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon image_export {
            get {
                object obj = ResourceManager.GetObject("image_export", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable This Image.
        /// </summary>
        public static string ImageEnableTooltip {
            get {
                return ResourceManager.GetString("ImageEnableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg;*.png;.
        /// </summary>
        public static string ImageExts {
            get {
                return ResourceManager.GetString("ImageExts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Folder(s)....
        /// </summary>
        public static string ImportFolderBtn_ToolTip {
            get {
                return ResourceManager.GetString("ImportFolderBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Folder.
        /// </summary>
        public static string ImportFolderDialogTitle {
            get {
                return ResourceManager.GetString("ImportFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Image(s)....
        /// </summary>
        public static string ImportImageBtn_ToolTip {
            get {
                return ResourceManager.GetString("ImportImageBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder has folders within it. Would you like to add those as well?.
        /// </summary>
        public static string ImportSubfoldersMessage {
            get {
                return ResourceManager.GetString("ImportSubfoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG (*.jpg).
        /// </summary>
        public static string JpegOutput {
            get {
                return ResourceManager.GetString("JpegOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Images....
        /// </summary>
        public static string MainWindow__fileBrowser_Title {
            get {
                return ResourceManager.GetString("MainWindow__fileBrowser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg;*.png.
        /// </summary>
        public static string MainWindow__watermarkFileBrowser_Filter {
            get {
                return ResourceManager.GetString("MainWindow__watermarkFileBrowser_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Watermark Image....
        /// </summary>
        public static string MainWindow__watermarkFileBrowser_Title {
            get {
                return ResourceManager.GetString("MainWindow__watermarkFileBrowser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name New Folder.
        /// </summary>
        public static string MainWindow_addFolderBtn_NewFolder_Title {
            get {
                return ResourceManager.GetString("MainWindow_addFolderBtn_NewFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Folder to Import.
        /// </summary>
        public static string MainWindow_FolderBrowser_Description {
            get {
                return ResourceManager.GetString("MainWindow_FolderBrowser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder has folders within it. Would you like to add those as well?.
        /// </summary>
        public static string MainWindow_importFolderBtn_Recursion_Ask {
            get {
                return ResourceManager.GetString("MainWindow_importFolderBtn_Recursion_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Folder.
        /// </summary>
        public static string MainWindow_importFolderBtn_Recursion_Ask_Title {
            get {
                return ResourceManager.GetString("MainWindow_importFolderBtn_Recursion_Ask_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string MainWindow_MainWindow_Output_Folder_Name {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Output_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to Output to.
        /// </summary>
        public static string MainWindow_OutputBrowser_Description {
            get {
                return ResourceManager.GetString("MainWindow_OutputBrowser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        public static string MainWindow_RenameFolderMenuItem_Title {
            get {
                return ResourceManager.GetString("MainWindow_RenameFolderMenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string New_Folder_Name {
            get {
                return ResourceManager.GetString("New_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name New Folder.
        /// </summary>
        public static string NewFolderDialogTitle {
            get {
                return ResourceManager.GetString("NewFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No File Set&gt;.
        /// </summary>
        public static string NoFileSet {
            get {
                return ResourceManager.GetString("NoFileSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        public static string OneHundredPercentLabel {
            get {
                return ResourceManager.GetString("OneHundredPercentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format.
        /// </summary>
        public static string OutputFormatHeader {
            get {
                return ResourceManager.GetString("OutputFormatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Quality.
        /// </summary>
        public static string OutputJpegQualityHeader {
            get {
                return ResourceManager.GetString("OutputJpegQualityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Output Location not Set).
        /// </summary>
        public static string OutputNotSetLabel {
            get {
                return ResourceManager.GetString("OutputNotSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputOptionLabel_Text {
            get {
                return ResourceManager.GetString("OutputOptionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Output Format.
        /// </summary>
        public static string OutputOverrideHeader {
            get {
                return ResourceManager.GetString("OutputOverrideHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {o} - Processed.
        /// </summary>
        public static string OutputTemplate {
            get {
                return ResourceManager.GetString("OutputTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:.
        /// </summary>
        public static string OutSettings_CustomNameSettings_ExampleLbl_Text {
            get {
                return ResourceManager.GetString("OutSettings_CustomNameSettings_ExampleLbl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template:.
        /// </summary>
        public static string OutSettings_CustomNameSettings_TemplateTxtBx_Text {
            get {
                return ResourceManager.GetString("OutSettings_CustomNameSettings_TemplateTxtBx_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Template Settings:.
        /// </summary>
        public static string OutSettings_CustomNameSettings_Title {
            get {
                return ResourceManager.GetString("OutSettings_CustomNameSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repalcement Codes:
        ///{o} - Original Filename
        ///{w} - Output Width
        ///{h} - Output Height.
        /// </summary>
        public static string OutSettings_CustomNameSettings_Tutorial_Text {
            get {
                return ResourceManager.GetString("OutSettings_CustomNameSettings_Tutorial_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Location:.
        /// </summary>
        public static string OutSettings_LocationBtn_Text {
            get {
                return ResourceManager.GetString("OutSettings_LocationBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Template.
        /// </summary>
        public static string OutSettings_NameOpt_CustOpt_Text {
            get {
                return ResourceManager.GetString("OutSettings_NameOpt_CustOpt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbered Sequentially.
        /// </summary>
        public static string OutSettings_NameOpt_NumOpt_Text {
            get {
                return ResourceManager.GetString("OutSettings_NameOpt_NumOpt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Filename.
        /// </summary>
        public static string OutSettings_NameOpt_OrigOpt_Text {
            get {
                return ResourceManager.GetString("OutSettings_NameOpt_OrigOpt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Naming Mode:.
        /// </summary>
        public static string OutSettings_NameOpt_Title {
            get {
                return ResourceManager.GetString("OutSettings_NameOpt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Settings.
        /// </summary>
        public static string OutSettings_Title {
            get {
                return ResourceManager.GetString("OutSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments Overridden.
        /// </summary>
        public static string OverriddenAdjustments {
            get {
                return ResourceManager.GetString("OverriddenAdjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Overridden.
        /// </summary>
        public static string OverriddenCrop {
            get {
                return ResourceManager.GetString("OverriddenCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Overridden.
        /// </summary>
        public static string OverriddenResize {
            get {
                return ResourceManager.GetString("OverriddenResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Overridden.
        /// </summary>
        public static string OverriddenWatermark {
            get {
                return ResourceManager.GetString("OverriddenWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Adjustments.
        /// </summary>
        public static string OverrideAdjustmentsHeader {
            get {
                return ResourceManager.GetString("OverrideAdjustmentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Crop.
        /// </summary>
        public static string OverrideCropHeader {
            get {
                return ResourceManager.GetString("OverrideCropHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Resize.
        /// </summary>
        public static string OverrideResizeHeader {
            get {
                return ResourceManager.GetString("OverrideResizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Watermark.
        /// </summary>
        public static string OverrideWatermarkHeader {
            get {
                return ResourceManager.GetString("OverrideWatermarkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphics (*.png).
        /// </summary>
        public static string PngOutput {
            get {
                return ResourceManager.GetString("PngOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Image Files|*.3fr;*.ari;*.arw;*.bay;*.crw;*.cr2;*.cap;*.dcs;*.dcr;*.dng;*.drf;*.eip;*.erf;*.fff;*.iiq;*.k25;*.kdc;*.mdc;*.mef;*.mos;*.mrw;*.nef;*.nrw;*.obm;*.orf;*.pef;*.ptx;*.pxn;*.r3d;*.raf;*.raw;*.rwl;*.rw2;*.rwz;*.sr2;*.srf;*.srw;*.x3f.
        /// </summary>
        public static string RawExts {
            get {
                return ResourceManager.GetString("RawExts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Image.
        /// </summary>
        public static string RemoveImageHeader {
            get {
                return ResourceManager.GetString("RemoveImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        public static string RemoveItemBtn_ToolTip {
            get {
                return ResourceManager.GetString("RemoveItemBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        public static string RenameFolderDialogTitle {
            get {
                return ResourceManager.GetString("RenameFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Resizing.
        /// </summary>
        public static string ResizeChck_ToolTip {
            get {
                return ResourceManager.GetString("ResizeChck_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ResizeDims_HeightUpDwn_Label {
            get {
                return ResourceManager.GetString("ResizeDims_HeightUpDwn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ResizeDims_WidthUpDwn_Label {
            get {
                return ResourceManager.GetString("ResizeDims_WidthUpDwn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string ResizeDimsLabel_Text {
            get {
                return ResourceManager.GetString("ResizeDimsLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact Size.
        /// </summary>
        public static string ResizeMode_ExactRadioBtn_Text {
            get {
                return ResourceManager.GetString("ResizeMode_ExactRadioBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larger Than.
        /// </summary>
        public static string ResizeMode_LargerRadioBtn_Text {
            get {
                return ResourceManager.GetString("ResizeMode_LargerRadioBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller Than.
        /// </summary>
        public static string ResizeMode_SmallerRadioBtn_Text {
            get {
                return ResourceManager.GetString("ResizeMode_SmallerRadioBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Mode:.
        /// </summary>
        public static string ResizeModeLabel_Text {
            get {
                return ResourceManager.GetString("ResizeModeLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string ResizeOptionLabel_Text {
            get {
                return ResourceManager.GetString("ResizeOptionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Settings.
        /// </summary>
        public static string ResizeSettings_Title {
            get {
                return ResourceManager.GetString("ResizeSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate All Images:.
        /// </summary>
        public static string RotateAllImagesLabel_Text {
            get {
                return ResourceManager.GetString("RotateAllImagesLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string RotateOptionLabel_Text {
            get {
                return ResourceManager.GetString("RotateOptionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180° Rotation.
        /// </summary>
        public static string RotationMenu_180RotationMenuItem_Header {
            get {
                return ResourceManager.GetString("RotationMenu_180RotationMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 270° Rotation.
        /// </summary>
        public static string RotationMenu_CCRotationMenuItem_Header {
            get {
                return ResourceManager.GetString("RotationMenu_CCRotationMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90° Rotation.
        /// </summary>
        public static string RotationMenu_CRotationMenuItem_Header {
            get {
                return ResourceManager.GetString("RotationMenu_CRotationMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Settings.
        /// </summary>
        public static string RotationMenu_DefaultRotationMenuItem_Header {
            get {
                return ResourceManager.GetString("RotationMenu_DefaultRotationMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Override.
        /// </summary>
        public static string RotationMenu_Header {
            get {
                return ResourceManager.GetString("RotationMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string RotationMenu_LandRotationMenuItem_Header {
            get {
                return ResourceManager.GetString("RotationMenu_LandRotationMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rotation.
        /// </summary>
        public static string RotationMenu_NoRotationMenuItem_Header {
            get {
                return ResourceManager.GetString("RotationMenu_NoRotationMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string RotationMenu_PortRotationMenuItem_Header {
            get {
                return ResourceManager.GetString("RotationMenu_PortRotationMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Settings.
        /// </summary>
        public static string RotationSettings_Title {
            get {
                return ResourceManager.GetString("RotationSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Rotation.
        /// </summary>
        public static string RotChck_ToolTip {
            get {
                return ResourceManager.GetString("RotChck_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAllBtn_ToolTip {
            get {
                return ResourceManager.GetString("SelectAllBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Selection.
        /// </summary>
        public static string SelectInvBtn_ToolTip {
            get {
                return ResourceManager.GetString("SelectInvBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Aspect Ratio.
        /// </summary>
        public static string SmartSizing_EnabledChk_Text {
            get {
                return ResourceManager.GetString("SmartSizing_EnabledChk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically swaps the width and height of the resize to match the longer and shorter dimension of the image..
        /// </summary>
        public static string SmartSizing_EnabledChk_ToolTip {
            get {
                return ResourceManager.GetString("SmartSizing_EnabledChk_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Sizing:.
        /// </summary>
        public static string SmartSizingLabel_Text {
            get {
                return ResourceManager.GetString("SmartSizingLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Processing.
        /// </summary>
        public static string StartBtn_Text {
            get {
                return ResourceManager.GetString("StartBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopBtn_Text {
            get {
                return ResourceManager.GetString("StopBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10%.
        /// </summary>
        public static string TenPercentLabel {
            get {
                return ResourceManager.GetString("TenPercentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged Image File Format (*.tiff).
        /// </summary>
        public static string TifOutput {
            get {
                return ResourceManager.GetString("TifOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200%.
        /// </summary>
        public static string TwoHundredPercentLabel {
            get {
                return ResourceManager.GetString("TwoHundredPercentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Selected Items.
        /// </summary>
        public static string UncheckBtn_ToolTip {
            get {
                return ResourceManager.GetString("UncheckBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Path Set&gt;.
        /// </summary>
        public static string ViewModel__outputPath__No_Path_Set {
            get {
                return ResourceManager.GetString("ViewModel__outputPath__No_Path_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Alignment.
        /// </summary>
        public static string WatermarkAlignmentHeader {
            get {
                return ResourceManager.GetString("WatermarkAlignmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable Watermarking.
        /// </summary>
        public static string WatermarkChck_ToolTip {
            get {
                return ResourceManager.GetString("WatermarkChck_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string WatermarkOpacityHeader {
            get {
                return ResourceManager.GetString("WatermarkOpacityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        public static string WatermarkOptionLabel_Text {
            get {
                return ResourceManager.GetString("WatermarkOptionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string WatermarkSettings_FontBtn_Text {
            get {
                return ResourceManager.GetString("WatermarkSettings_FontBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File:.
        /// </summary>
        public static string WatermarkSettings_ImageBtn_Text {
            get {
                return ResourceManager.GetString("WatermarkSettings_ImageBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Greyscale.
        /// </summary>
        public static string WatermarkSettings_ImageGreyChk_Text {
            get {
                return ResourceManager.GetString("WatermarkSettings_ImageGreyChk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string WatermarkSettings_ImageOpt_Text {
            get {
                return ResourceManager.GetString("WatermarkSettings_ImageOpt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Options.
        /// </summary>
        public static string WatermarkSettings_ImageOpts_Title {
            get {
                return ResourceManager.GetString("WatermarkSettings_ImageOpts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity:.
        /// </summary>
        public static string WatermarkSettings_OpacUpDwn_Text {
            get {
                return ResourceManager.GetString("WatermarkSettings_OpacUpDwn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Options.
        /// </summary>
        public static string WatermarkSettings_OtherOpts_Title {
            get {
                return ResourceManager.GetString("WatermarkSettings_OtherOpts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string WatermarkSettings_TextBox_Text {
            get {
                return ResourceManager.GetString("WatermarkSettings_TextBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string WatermarkSettings_TextOpt_Text {
            get {
                return ResourceManager.GetString("WatermarkSettings_TextOpt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Options.
        /// </summary>
        public static string WatermarkSettings_TextOpts_Title {
            get {
                return ResourceManager.GetString("WatermarkSettings_TextOpts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Settings.
        /// </summary>
        public static string WatermarkSettings_Title {
            get {
                return ResourceManager.GetString("WatermarkSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string WatermarkSettings_TypeLabel_Text {
            get {
                return ResourceManager.GetString("WatermarkSettings_TypeLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Text.
        /// </summary>
        public static string WatermarkText {
            get {
                return ResourceManager.GetString("WatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        public static string ZeroPercentHeader {
            get {
                return ResourceManager.GetString("ZeroPercentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        public static string ZeroPercentLabel {
            get {
                return ResourceManager.GetString("ZeroPercentLabel", resourceCulture);
            }
        }
    }
}
