//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchImageProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchImageProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg.
        /// </summary>
        internal static string MainWindow__fileBrowser_Filter {
            get {
                return ResourceManager.GetString("MainWindow__fileBrowser_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Images....
        /// </summary>
        internal static string MainWindow__fileBrowser_Title {
            get {
                return ResourceManager.GetString("MainWindow__fileBrowser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg;*.png.
        /// </summary>
        internal static string MainWindow__watermarkFileBrowser_Filter {
            get {
                return ResourceManager.GetString("MainWindow__watermarkFileBrowser_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Watermark Image....
        /// </summary>
        internal static string MainWindow__watermarkFileBrowser_Title {
            get {
                return ResourceManager.GetString("MainWindow__watermarkFileBrowser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name New Folder.
        /// </summary>
        internal static string MainWindow_addFolderBtn_NewFolder_Title {
            get {
                return ResourceManager.GetString("MainWindow_addFolderBtn_NewFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Folder to Import.
        /// </summary>
        internal static string MainWindow_FolderBrowser_Description {
            get {
                return ResourceManager.GetString("MainWindow_FolderBrowser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder has folders within it. Would you like to add those as well?.
        /// </summary>
        internal static string MainWindow_importFolderBtn_Recursion_Ask {
            get {
                return ResourceManager.GetString("MainWindow_importFolderBtn_Recursion_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Folder.
        /// </summary>
        internal static string MainWindow_importFolderBtn_Recursion_Ask_Title {
            get {
                return ResourceManager.GetString("MainWindow_importFolderBtn_Recursion_Ask_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        internal static string MainWindow_MainWindow_Output_Folder_Name {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Output_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to Output to.
        /// </summary>
        internal static string MainWindow_OutputBrowser_Description {
            get {
                return ResourceManager.GetString("MainWindow_OutputBrowser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        internal static string MainWindow_RenameFolderMenuItem_Title {
            get {
                return ResourceManager.GetString("MainWindow_RenameFolderMenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string New_Folder_Name {
            get {
                return ResourceManager.GetString("New_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Path Set&gt;.
        /// </summary>
        internal static string ViewModel__outputPath__No_Path_Set {
            get {
                return ResourceManager.GetString("ViewModel__outputPath__No_Path_Set", resourceCulture);
            }
        }
    }
}
